### ISSUE TITLE
Creating a new village

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#10]
When creating a village it would be useful if the software could pick up the country already listed for the assessment rather than having to add it each time!

**Comment by Zerodriven** [comment]
Hi @jlhems 

We'll be looking at adding this to the next release.

Thanks.

**Comment by jlhems** [comment]
Thanks!

**Comment by Zerodriven** [comment]
Going to close this as the development has been completed and QAd. It'll be available in the next release.
