### ISSUE TITLE
Village Record State

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#11]
What is the purpose of the Village Record State? Looks like it’s only possible to save the screen for an added village when this is selected but there’s no prompt to tell the user a choice has to be selected, the save button just flashes each time you try to save. Useful if all mandatory fields could have a red star as per standard website functionality.

**Comment by Zerodriven** [comment]
Hi @jlhems 

We're actually going to be removing this as per the original Cost of The Diet software to avoid confusion moving forward. Thanks for pointing this out.

Thanks.

**Comment by jlhems** [comment]
Thanks. Will you be marking all mandatory fields in the next version/release?

**Comment by Zerodriven** [comment]
Heya,

![image](https://user-images.githubusercontent.com/17741755/131800759-facee0bf-c1f3-4f48-a63a-88ffa45be78e.png)

We've made each field (on the edit too) mandatory. So if you don't fill it in you'll get the red boxes and you won't be able to press the save button until each item has been filled out.

Thanks,
Jason.

**Comment by jlhems** [comment]
Thanks Jason. Hoping to test again today, will take a look.

**Comment by Zerodriven** [comment]
Not an issue.

As of right now the client doesn't automatically update (This is on our list of things we want to get working sooner than later) so you'll need to redownload a new version of it once it's available. So if you could keep testing on your current version that would be great. Once we're in a position to release an update for testing we'll let you know, we also include a change list with every version so you'll get a high-level overview of what's actually included.

Thanks,
Jason.

**Comment by jlhems** [comment]
That's fine, I'll continue with the current testing version.

**Comment by Zerodriven** [comment]
Closing this ticket. Development has been completed and QAd - Will be in the next available release.
