### ISSUE TITLE
Assessment set-up screen

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#12]
Is there/will there be a summary assessment set up screen where an overview of the assessment data can be viewed e.g. assessment name, location, markets, villages etc ? This is v useful in the current software.

**Comment by Zerodriven** [comment]
Hi @jlhems 

We've added this to our backlog of items to look at. It should be in the next release or two. Once this has been done we'll update this ticket to let you know..

Thanks.
