### ISSUE TITLE
Market Survey default unit and date

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#14]
Is it possible to include grams as the default unit in the Market Surveys (as per old software, see Fig2) to save the user having to select it each time? If nothing is selected there’s no prompt so it’s not clear which unit the software is using. Also, although I selected g or ml for some of my entries, when I've gone back to the Market Surveys the unit is blank (see Fig3). Appreciate this may still being worked on.

The survey date is defaulting to the day before (see Fig3) once accepted, even though today's date is selected and saved (see Fig4). 

<img width="930" alt="Fig2 Grams default in old CotD" src="https://user-images.githubusercontent.com/89542648/130954979-cab081b2-8160-4992-b5ed-d8c307a18c8f.PNG">
<img width="959" alt="Fig3 Market Survey" src="https://user-images.githubusercontent.com/89542648/130954983-312e32e4-a4fc-499e-af45-d17cab4812e4.PNG">
<img width="933" alt="Fig4 Market Survey date" src="https://user-images.githubusercontent.com/89542648/130954984-4142db12-ee56-4eaf-b6e3-95ba5ae97f49.PNG">

**Comment by Zerodriven** [comment]
Hi @jlhems 

This has been added to our backlog and will be looked at. Thanks for the feedback,

Cheers.

**Comment by DavidKavanagh** [comment]
Both of these issues have now been fixed
