### ISSUE TITLE
Diet Surveys

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#15]
The same date issue as reported for the Market Surveys is occurring in the Diet Surveys i.e. defaulting to the day before.

The 'Accepted' Diet Survey is not registering as entered or completed (see Figs5&6).

<img width="912" alt="Fig5 Completed Diet Survey" src="https://user-images.githubusercontent.com/89542648/130955705-6a6bbec0-953c-42b4-ac8c-852324596716.PNG">
<img width="452" alt="Fig6 Diet Survey not showing" src="https://user-images.githubusercontent.com/89542648/130955707-4b97dd8e-d021-4723-9ff8-b7ab2b5293b9.PNG">

**Comment by Zerodriven** [comment]
Hi @jlhems 

Thanks for letting us know about this, we'll take a look into it.

Cheers.

**Comment by DavidKavanagh** [comment]
These issues has now been fixed.
