### ISSUE TITLE
Market Surveys Summary

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#16]
Will it be possible to export the market survey summaries to an excel table in the next stage of the software build? This is an essential function to enable proper data checking and cleaning and to produce graphs etc.

The g and ml units also need to translate from the market survey data to the market survey summaries.

**Comment by Zerodriven** [comment]
Hi @jlhems -

I've passed this onto our developers who will take a look at this. Once we've completed it we'll update this ticket to let you know.

Cheers.

**Comment by jlhems** [comment]
Thanks for this Justin and your comments from my other issues raised.

**Comment by DavidKavanagh** [comment]
This has now been implemented.
