### ISSUE TITLE
Wealth groups info

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#17]
Hi, would it be possible to add the wealth groups info directly in the row against the relevant group rather than clicking on a link to add this info? Takes away an unnecessary click for the user!

**Comment by DavidKavanagh** [comment]
We have made this change for some of the other pages (such as Seasons), so we should do it for Wealth Groups too for consistency.

**Comment by DavidKavanagh** [comment]
Fixed in v3.0.5
