### ISSUE TITLE
Family info

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#18]
Like this screen, easy to use and add family and like the way the PLW reqs automatically appear when a woman is selected

**Comment by Zerodriven** [comment]
Heya,

Can we have some screenshots please?

Cheers,,
Jason

**Comment by jlhems** [comment]
Hi Jason

What would you like screenshots of? I was commenting that I like the way this screen works, intuitive use etc. No action needed!

**Comment by Zerodriven** [comment]
Hi,

Oh! Even better then! I'll feedback to the team!

Thanks
Jason
