### ISSUE TITLE
Standard analysis - percentage nutrient req report

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#19]
Hi, this is currently only working at the individual level. No output at the Total level

**Comment by Zerodriven** [comment]
Hi,

Would you be able to attach an image please?

Thanks,
Jason

**Comment by jlhems** [comment]
Hi Jason

Attached. I've also highlighted where the columns don't line up, tho could be my screen size.
<img width="1112" alt="Fig7 Total Report for Percentage Nutrient Requirement" src="https://user-images.githubusercontent.com/89542648/131825963-1a2ae127-f742-4644-a499-81d73b1845a2.PNG">

**Comment by Zerodriven** [comment]
Hi!

Apologies for the late reply, I've attached this to our backlog so the team can look at this.

Thanks,
Jason

**Comment by DavidKavanagh** [comment]
These issues do now appear to have been resolved.
