### ISSUE TITLE
Exporting standard analysis reports

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#20]
Similar to one of my previous comments, will it be possible to export standard (and eventually modelling) analysis reports to excel and rtf/or Word? These are essential for including in the assessment reports. Appreciate not the full report functionality isn't included in this release.
Thanks!

**Comment by DavidKavanagh** [comment]
From what I can see, we now have the same export capability as the original Delphi application. If that is not the case, please raise a new ticket including the location in the Delphi application where we can see a missing export in action. Thanks.
