### ISSUE TITLE
Portions warning in standard analysis

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#21]
The current software includes a portions warning (see Fig8 attached) in the analysis for the Daily or Weekly detailed diet (see Fig9). Will this and the red highlight be included in the new software? 

<img width="517" alt="Fig8 Portions warning" src="https://user-images.githubusercontent.com/89542648/131828519-671b4971-91c4-48bb-90ce-a0971e2e8a51.PNG">

<img width="676" alt="Fig9 Detailed daily diet" src="https://user-images.githubusercontent.com/89542648/131828876-9019dbce-48f2-4800-97ea-361b363b86bc.PNG">

**Comment by DavidKavanagh** [comment]
This has now been implemented
