### ISSUE TITLE
Creating a New Assessment - New Assessment

### ISSUE THREAD

**Issue by Masud-SCUK** [SaveTheChildrenUK/CostOfTheDiet#22]
Just the plus sign might not be immediately obvious. Can we also add another button saying 'New Assessment' or something similar in words? not the biggest deal though.

**Comment by Zerodriven** [comment]
Heya,

I've passed this to our developers.

Thanks,

Jason

**Comment by DavidKavanagh** [comment]
Added to ADO as issue 4005

**Comment by DavidKavanagh** [comment]
The plus sign was replaced with a clearer "Create New Assessment" button in v3.0.4
