### ISSUE TITLE
New Assessment - Adding Seasons

### ISSUE THREAD

**Issue by Masud-SCUK** [SaveTheChildrenUK/CostOfTheDiet#24]
when adding multiple seasons one after another, we can't see the dates we have selected for previously added seasons - it might make things a little bit difficult to cross-check if/what mistakes we have made with dates. It would be good to see previously added seasons with all the details when adding a new season.

**Comment by Zerodriven** [comment]
Hi Masud,

Good idea!

Thanks for the suggestion, we didn't think of this. I'll attach it to our backlog so the team can look into this and hopefully get it into a release sooner than later.

Thanks,
Jason
