### ISSUE TITLE
New Assessment - Adding Villages: 

### ISSUE THREAD

**Issue by Masud-SCUK** [SaveTheChildrenUK/CostOfTheDiet#25]
can the country field be automatically be filled from the assessment information that we have filled at the beginning?

**Comment by Zerodriven** [comment]
Hi Masud,

Just to let you know that we've already completed this piece of work in our development build, the next announced version will have this included!

Thanks,
Jason

**Comment by Masud-SCUK** [comment]
Thanks, Jason - Sorry I am just trying the software now - maybe it would have been better if I had commented earlier? Either way, I am glad that you have spotted it and completed the task. Masud
