### ISSUE TITLE
New Assessment - Adding a Food List / New Food: Filter by Food Groups

### ISSUE THREAD

**Issue by Masud-SCUK** [SaveTheChildrenUK/CostOfTheDiet#27]
I can't seem to find an option to filter food items by "Food Groups". For example, if I want to add a few vegetables, it would be easier to just look at the list of vegetables only.

**Comment by Masud-SCUK** [comment]
Found the option to filter later - maybe it would be good to have them exposed by default

**Comment by Zerodriven** [comment]
Hi Masud,

I'll pass this to our developers (I'll also cancel the other ticket as it's functionally the same)

Thanks,
Jason

**Comment by DavidKavanagh** [comment]
The filter options are now shown at all times so hopefully this will be clearer now.
