### ISSUE TITLE
New Assessment - Adding Multiple Seasons: 

### ISSUE THREAD

**Issue by Masud-SCUK** [SaveTheChildrenUK/CostOfTheDiet#28]
when adding multiple seasons, it appears that the software lets you create more than one season even if the total number of days doesn't add up to be 356 days. I have created only two seasons that doesn't cover the whole year. In one had, I find it easier not to be forced by the software to create a season (covering certain months) even if I don't need it (which was the case in the last version), but wondering if it will cause problems during the analysis phase.

**Comment by Zerodriven** [comment]
Hi Masud,

Any chance you could attach a screenshot of your season listing so I can see what you mean?

Thanks,
Jason

**Comment by Jusjoy** [comment]
Hi Masud,

The requirement was to put a total of 365 days for all the seasons combined. The reports will only come up based on the seasons which are been entered in to the assessment.

Cheers

Justin.

**Comment by DavidKavanagh** [comment]
This has now been resolved. If only a single season is provided, then it does not need to cover the entire year - the analysis will just assume it is a full year. If more than one season is provided, then the seasons must cover the entire year without gaps or overlaps.
