### ISSUE TITLE
Adding food to assessment - Editing Food Details:

### ISSUE THREAD

**Issue by Masud-SCUK** [SaveTheChildrenUK/CostOfTheDiet#30]
Editing Food Details: Once I have added food to the assessment, I don't seem to be able to edit basic food details - especially the local name/other names? This is actually very important, as we need to add local names in local language (Unicode) for it to be reflected in the questionnaire.

**Comment by Zerodriven** [comment]
Hi Masud,

This is actually something we've got planned to add in in our next announced release.

Thanks for raising it, I'll show it to the team so we can prioritise too.

Thanks,
Jason

**Comment by DavidKavanagh** [comment]
This has now been implemented in the "Set Local Name for Food" page.
