### ISSUE TITLE
Market Surveys - Data Entry: 

### ISSUE THREAD

**Issue by Masud-SCUK** [SaveTheChildrenUK/CostOfTheDiet#31]
Once we copy data from one season to the next, is it possible to highlight in which food items the prices change by season - here I mean is it possible to highlight the price/weight fields (as is is often a bit difficult to track the tick box (weight/price change across season) at the end of the row?

**Comment by Zerodriven** [comment]
Hi Masud,

I'll pass this one over to our developers.

Thanks,
Jason

**Comment by DavidKavanagh** [comment]
We do now copy over the setting for the "Does the price or weight changes across the seasons?". This is the same approach taken by the Delphi application and seems relatively clear. But if you had something else in mind then please let us know,
![image](https://github.com/SaveTheChildrenUK/CostOfTheDiet/assets/20168917/3dfd707e-b44a-4f98-8779-8d2162859606)
