### ISSUE TITLE
Adding/editing family members:

### ISSUE THREAD

**Issue by Masud-SCUK** [SaveTheChildrenUK/CostOfTheDiet#32]
Can you please lift the restriction on how many family members can be added? In some cases, I previously had to create families with 26 members, and if we impose restrictions in this version, we will not be able to do those analyses anymore.

**Comment by Zerodriven** [comment]
Hi,

This is actually something we've taken from the original piece of software (Which by default had a limit of 15 but could be tweaked).

We are currently in the process of adding assessment constraints as per the original application which will let you define these yourself. The next announced version should hopefully let you set this to as high as you want.

Thanks,
Jason.

**Comment by DavidKavanagh** [comment]
There is no longer a limit on the number of family members that can be added. .
