### ISSUE TITLE
Test calculations in both versions of the software

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#33]
Hi Justin

Attached are the two images of the standard analysis calculations in both versions of the software. They look fine to me, no errors when I go into each diet in the new software. I can send images for each separate diet with family members etc. if you want to see them.

<img width="922" alt="Fig10 Std analysis calculation_old software" src="https://user-images.githubusercontent.com/89542648/134143920-512671f8-a994-47f1-ac17-5ffb129a62ca.PNG">
<img width="995" alt="Fig11 Std analysis calculation_new software" src="https://user-images.githubusercontent.com/89542648/134143927-4adae820-cdb0-4d04-a1bf-c0c0599bb0af.PNG">

**Comment by DavidKavanagh** [comment]
In the early days of the software, we had some discrepancies in the calculated diet compared to Delphi. We believe they have now all been resolved so please raise a new ticket if you continue to see any differences.
