### ISSUE TITLE
Ticket 3463 - Adding season name and number/order

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#36]
Creating a new assessment again...adding the season name and number/order doesn't always work. Worked initially, I wanted to change the order of the seasons so deleted the two I'd created and then wasn't able to add the season name and number to the re-created seasons.  The relevant boxes weren't greyed out but couldn't add any text.
<img width="1043" alt="Season name and number" src="https://user-images.githubusercontent.com/89542648/161996906-82379538-41e5-46a8-8bde-ebf4b9df8135.PNG">

**Comment by jlhems** [comment]
After a few minutes then able to add (see image) but this page is glitching.
<img width="1128" alt="Season name and number_v2" src="https://user-images.githubusercontent.com/89542648/161997516-4293501b-4b8d-43c5-b977-b23d94340b17.PNG">

**Comment by Zerodriven** [comment]
Note: When you set the "active" season that makes it the default (in-use) season and moves it to the top of the season order and is the one used in any calculation where season order is required - Hope that makes sense.

**Comment by jlhems** [comment]
I can't see where to re-order. I've now created two seasons. It seems to order them in alpha order rather than season or date order. Or does it order by active season?
<img width="1087" alt="season order" src="https://user-images.githubusercontent.com/89542648/161998362-f0b47fbe-ac36-403d-9b65-b1f92ba50ed7.PNG">

**Comment by jlhems** [comment]
Thanks, our messages crossed

**Comment by Zerodriven** [comment]
Might be worth feeding this back (Formally?) - Identifying the active season isn't clear. Maybe some sort of colour change for the active season? There might also need to be training around this sort of stuff moving forward too.

**Comment by jlhems** [comment]
Agree, it's not that intuitive. What's the process for feeding back formally? We can discuss next week when we meet with Deborah if that's easier. Thanks

**Comment by jlhems** [comment]
The system seems to order it, I couldn't see an option to re-order it myself e.g. with up and down arrows.

**Comment by Zerodriven** [comment]
![image](https://user-images.githubusercontent.com/17741755/162002330-78c947e2-8a5e-4fb7-a2c7-577b9d5e5e85.png)

Click into a season (all added)

![image](https://user-images.githubusercontent.com/17741755/162002401-73053cbb-6f36-4ac4-813e-37ad8c9b1749.png)

Click the up/down arrow in the order by and then save. It now re-orders:

![image](https://user-images.githubusercontent.com/17741755/162002555-979675c2-17a0-41a8-97c9-233c6dc3dbf3.png)

The up/down arrow - If you send that as a suggestion!

**Comment by Zerodriven** [comment]
Okay cool - If you go into one of the seasons when you've added them and click into "Order" - You should see an up and down arrow, click that to re-order.

I've found a problem (Now in our backlog) where the order doesn't order properly (The active goes first but then the rest don't) - So we'll add that to our fix list.

**Comment by jlhems** [comment]
Yes, by season order. As you say, it's not ordering properly yet. I don't think it's very intuitive to go into the seasons individually to re-order though. I would expect to see the re-ordering option on the seasons front screen. Sorry if I'm complicating things! I'm not sure how much user testing (if any?) was done on this new layout. Something I'd like to discuss before we move too much further ahead with me testing the software side. I won't add any more data at this stage until I've got the notes on how to transfer the db. Hope that's OK. 
Thanks, Jacky

**Comment by Zerodriven** [comment]
I've added that (specifically) to our backlog to be fixed. 

Regarding the database: I was talking between the new versions of the software - Not the old one and the new one (We're not there yet) so if you could please keep testing.

Thanks,
Jason.

**Comment by jlhems** [comment]
Yes, I thought this is what you meant. Have you sent the notes on how to transfer between the new version? Thanks.

**Comment by DavidKavanagh** [comment]
This screen has now been completely redesigned
