### ISSUE TITLE
See #35 - same issue occurring in v2.3.2

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#37]
Hi Jason, I've just added a comment to a Closed Issue, do these still come through to you? Still can't add Markets in v.2.3.2

**Comment by Zerodriven** [comment]
Heya,

Can you click on the cog on the top right of the app and confirm the version is .3.2 please?

Cheers
Jason

**Comment by jlhems** [comment]
Yes, I checked the version - it's definitely 2.3.2

**Comment by DavidKavanagh** [comment]
This appears to be working fine in v3.0.0
