### ISSUE TITLE
Adding foods to assessments

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#38]
Would it be possible to move the 'select foods for assessment' button to above the 'search foods in assessment' area? (see 1st attachment)? It's not that obvious when first on the page where to start adding foods. As a user, my eyes are drawn to the top left of the page where the search option is.

I don't think it's obvious to users where to add foods once on the 2nd attached page. 

Overall, I find the adding foods area confusing and not intuitive. I appreciate these aren't testing/functionality issues, something to raise with Deborah, Michael and probably Lilly.

<img width="1049" alt="Adding foods_1" src="https://user-images.githubusercontent.com/89542648/162629409-6f496db2-976e-4af7-9869-53dbce70500d.PNG">
<img width="1051" alt="Adding foods_2" src="https://user-images.githubusercontent.com/89542648/162629410-024f9dc7-60de-420f-9bf0-08b3bdc20a0c.PNG">

**Comment by Zerodriven** [comment]
Heya - Foods is one of those areas under a lot of discussion within the team because for something so simple it's actually quite complicated and we want to further improve it. 

If you have any suggestions on ways to improve it we'd love to hear.

**Comment by jlhems** [comment]
Thanks Jason. Realised I logged the same user interface issues last August! (see #13) Good to hear about improving this section. What's not clear is whether this is within the remit of what I'm doing now and if these screens can be changed before the first launch. I'll email Michael and Lilly and cc you and Deborah.

**Comment by DavidKavanagh** [comment]
This button has now been moved.
![image](https://github.com/SaveTheChildrenUK/CostOfTheDiet/assets/20168917/e4b1c75c-0fc6-419e-ba3b-876d6c1e2bb9)
