### ISSUE TITLE
Market naming convention

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#39]
The market naming isn't consistent - on the entry page the label is 'sub-location' (see 1st attachment), on the list page it shows as 'region' (see 2nd attachment). For consistency with the previous software, this should be labelled sub-location throughout. Thanks.
<img width="1090" alt="Market name1" src="https://user-images.githubusercontent.com/89542648/162725875-d8145453-9f4e-4534-83ad-c650bfb38912.PNG">
<img width="941" alt="Market name2" src="https://user-images.githubusercontent.com/89542648/162725881-aa7284aa-87eb-420c-a98e-17401fcc65ae.PNG">

**Comment by jlhems** [comment]
For consistency with other entry sections e.g. Villages, please change 'Name' to Market name' both on the entry page and list page.
The Villages sub-location also shows as Region on the list page. Again, this should be changed to 'Sub-location' throughout please.

**Comment by DavidKavanagh** [comment]
This has been partially fixed - Sub-location now appears to be used consistently rather than Region.
However, Name has not yet been changed to Market Name to be consistent with the Village pages.

**Comment by DavidKavanagh** [comment]
Fixed in v3.0.2
