### ISSUE TITLE
'Last updated' not updating

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#40]
Hi Jason

I've been working on the foods list this AM but the 'Last Updated' date on the home screen is still showing Monday's date (see attached).
<img width="1051" alt="Last updated date" src="https://user-images.githubusercontent.com/89542648/163377839-1cc422e8-c61a-4b17-8c3a-c8b8f9ceda15.PNG">

**Comment by Zerodriven** [comment]
Heya - Thanks for this - I've passed it to the development team to look at.

**Comment by DavidKavanagh** [comment]
This appear to be fixed in v3.0.0
