### ISSUE TITLE
Adding Market Survey data

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#41]
Hi Jason - the list of foods under the first market, first trader contains only 2 food groups (see 1st image), I've randomly checked others markets and traders and they look fine (see 2nd image for correct list). I initially thought it may be due to the number of seasons with the active season showing in the 2nd column. I've deleted the other seasons and still getting the same issue.

On a separate issue, please could we talk about aesthetics/layout at our next meeting - I think the local and English name columns need more space. Could the weight and price boxes be made smaller to create space for this? And please could the food group name headings either be shaded or larger font/in bold so they stand out?

<img width="1058" alt="Missing food list_market survey data" src="https://user-images.githubusercontent.com/89542648/163390720-a73353a8-7dfb-440c-b860-3cb640c8ce63.PNG">
<img width="1110" alt="Correct food list_market survey data" src="https://user-images.githubusercontent.com/89542648/163390744-e432bb30-8239-436b-8290-bf1dbc125ef8.PNG">

**Comment by Zerodriven** [comment]
Heya - Assigned this to our developers to look at. Cheers.

**Comment by DavidKavanagh** [comment]
This appears to have been resolved by v3.0.0.
