### ISSUE TITLE
Diet Surveys/Dietary Habits naming convention

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#43]
Hi - the naming convention for the Dietary Habits Interviews should be consistent (see image). In the original software the relevant section is named 'Dietary Habits interviews'. The Diet Survey section and headings within this should be renamed as per the original software for consistency. Thanks.

<img width="660" alt="Diet surveys labels" src="https://user-images.githubusercontent.com/89542648/163844416-ad70ffe3-53d4-4ea9-9385-99e727d5a539.PNG">

**Comment by Zerodriven** [comment]
Heya - Assigned this to our developers to look at. Cheers.

**Comment by DavidKavanagh** [comment]
This has now been resolved:
![image](https://user-images.githubusercontent.com/20168917/176872602-55d5d50b-255d-46e2-b2a2-6b80a3d15e24.png)
