### ISSUE TITLE
Diet Surveys saving/accept

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#44]
Hi - is it possible to choose accept, even if all data isn't available to enter? Even though a couple of fields are missing, I've entered all the data I've got so want to accept it but it's greyed out (see 1st image). This then means that every time I hit the back button the unsaved data warning pops up (see 2nd image) and none of the surveys/interviews are showing as complete, only as draft (see 3rd image). 
There also seems to be an issue with the survey date - I've tried a number of times to enter today's date (18/04/2022) and it keeps reverting to 17/04/2022 (see 4th & 5th images) - this might be what's causing the unsaved data warning. If I say 'OK ' to unsaved changes, the date changes from 18/04 to 17/04 when I leave the page. Hope this makes sense!

<img width="937" alt="Diet habits_accept button" src="https://user-images.githubusercontent.com/89542648/163846128-c188464e-a7f6-4e12-a781-58d4fa5435c8.PNG">
<img width="1002" alt="Diet habits_unsaved changes" src="https://user-images.githubusercontent.com/89542648/163846194-e7d553fe-e3a5-49a7-965d-45ea373711db.PNG">
<img width="203" alt="Diet survey draft v complete" src="https://user-images.githubusercontent.com/89542648/163846231-fa048023-c738-4045-98ad-6490d4d52744.PNG">
<img width="760" alt="Diet surveys_incorrect date1" src="https://user-images.githubusercontent.com/89542648/163846474-425d008d-45cf-4882-89db-e5841f7df13e.PNG">
<img width="994" alt="Diet surveys_incorrect date2" src="https://user-images.githubusercontent.com/89542648/163846479-ea1223c1-26dc-44f2-bf9b-a5f1585785c2.PNG">

**Comment by Zerodriven** [comment]
Heya - Assigned this to our developers to look at. Cheers.

**Comment by jlhems** [comment]
Many thanks for assigning all these.

**Comment by jlhems** [comment]
Hi - the 'accept' button is no longer showing. Now appears as 'Save & Close' (see image). Will there be an option to accept to enable Completed versions of the dietary habits data?
<img width="967" alt="Diet survey_save_close" src="https://user-images.githubusercontent.com/89542648/164201310-23e0ec8b-dc5c-4a2b-8a17-eb7ea1315705.PNG">

**Comment by jlhems** [comment]
This would be consistent with the Market Survey data which uses the 'accept' button in the new software. the old software had a 'save/accept' button.

**Comment by jlhems** [comment]
When saving dietary habits survey data the 1st image message appears re: erroneous records. The old software tells the user how many erroneous records there are which is helpful (see 2nd image). Is it possible to include the number of records in the new software?
<img width="893" alt="Diet Survey - data incomplete" src="https://user-images.githubusercontent.com/89542648/164202156-64768874-d368-4b6b-a5db-993fb2d3b815.PNG">
<img width="838" alt="Diet Survey - data incomplete2" src="https://user-images.githubusercontent.com/89542648/164202188-e8320378-86ed-4540-943b-d1d6bde19cde.PNG">

**Comment by DavidKavanagh** [comment]
This has mostly now been implemented. The only part remaining is that it does not specify the number of erroneous records. That remains in the backlog (ticket #3550)

**Comment by DavidKavanagh** [comment]
This appears to have been resolved by v3.0.0, except for the lack of an Accept button. This was removed to make it consistent with the Delphi application. If you feel an Accept button would be useful, please raise that as a new ticket and we'll discuss it with the product owner.
