### ISSUE TITLE
PLW requirements in 'Add Family' screen

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#45]
Hi - I can't see where to add the PLW requirements within the add family screen. This was a separate field selection under 'Select an individual' in the old software (see image). Please advise.

<img width="1115" alt="PLW reqs old software" src="https://user-images.githubusercontent.com/89542648/164213051-c52c8291-97c0-48ba-8aaa-eaf1a30c329b.PNG">

**Comment by DavidKavanagh** [comment]
This appears to have been resolved:
![image](https://user-images.githubusercontent.com/20168917/176870457-7b491dc0-dc6b-4efb-bf44-3cc72e9b9909.png)
