### ISSUE TITLE
Adding wealth groups

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#46]
Hi - is there any reason the figures for the wealth groups can't be added on the landing screen? This was possible in the old software. Clicking on the wealth group category seems to be adding an extra unnecessary step for the user. I would also expect to be able to sort the order on the landing screen rather than going into each wealth group to change this. In the old software, changing the order was changed by clicking an up arrow, in the new version it's possible to have two or more groups in the same position (see image). It doesn't auto change.

<img width="921" alt="Wealth groups" src="https://user-images.githubusercontent.com/89542648/164214841-88854e92-3900-41a8-9b94-dc594065931a.PNG">

**Comment by jlhems** [comment]
Is it also possible to add the currency info in brackets for the income and NFE amounts? This is helpful and is consistent with the old software - see image
<img width="1126" alt="Wealth groups currency" src="https://user-images.githubusercontent.com/89542648/164255019-48e8f802-5ffe-42ea-883a-b6f3ffd68e77.PNG">

**Comment by DavidKavanagh** [comment]
The order of the wealth groups can now be changed but the other points still remain unresolved.

**Comment by DavidKavanagh** [comment]
The first issue is the subject of a separate ticket #17 so I'll leave the discussion of that issue to that ticket.
The second issue, the lack of currency info, remains unresolved.

**Comment by DavidKavanagh** [comment]
The currency issue has now been fixed in v3.0.3
