### ISSUE TITLE
Default unit missing in Market Surveys

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#47]
Hi - the default unit (g) is missing from the Market Surveys (see 1st image). It was showing for the data I entered yesterday (see 2nd image). Checked other Market Surveys created but no data entered yet and nothing is showing under the Unit column,

<img width="978" alt="Default unit missing" src="https://user-images.githubusercontent.com/89542648/164487537-c3a8e1e2-23ab-47f1-a0a4-f5515d0be079.PNG">
<img width="987" alt="Default unit showing" src="https://user-images.githubusercontent.com/89542648/164487619-1e94c782-81c4-46e4-8234-8947b5f6705d.PNG">

**Comment by jlhems** [comment]
Hi - this seems to be OK again now. I'll check again though as I continue to enter market data.

**Comment by jlhems** [comment]
This issue has occurred again this afternoon (see attached). I've been entering market data for the last 2 days and it was fine, only re-occurred again late this afternoon.
<img width="1004" alt="Default unit missing_v2" src="https://user-images.githubusercontent.com/89542648/165564366-19da5a98-d499-42e6-9d97-952904c2633d.PNG">

**Comment by DavidKavanagh** [comment]
This should now be fixed in version 2.3.6
