### ISSUE TITLE
Saving family members

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#51]
Once family members are added, the page hangs after clicking 'Save' (see attached). It's been like this for about 10 minutes. Clicking on Back loses all changes/additions and 'saving changes' still hangs on the page (see 2nd attachment).
<img width="948" alt="Saving family members" src="https://user-images.githubusercontent.com/89542648/176654719-8c370144-4380-41dd-b951-1cdadacefead.PNG">
<img width="899" alt="Family members after Back button" src="https://user-images.githubusercontent.com/89542648/176654740-ca1f29ff-9610-456b-963a-fbd04d7971ae.PNG">

**Comment by jlhems** [comment]
PS - adding PLW reqs looks good, easy to use and add. Thanks!

**Comment by jlhems** [comment]
When refreshing to update costs I've noticed that the number of family members showing on the model page is 21 (see attached). Seems that the software is picking up the 3 times I've tried to add family members but the individuals aren't showing in the relevant screen or in the Model Details screen (highlighted in original comment).
<img width="639" alt="No of family members" src="https://user-images.githubusercontent.com/89542648/176657822-182913cb-a758-4877-8533-6072270e4e86.PNG">

**Comment by DavidKavanagh** [comment]
Some further work has been done on this and will be included in the next release 
ADO Ticket 3954

**Comment by DavidKavanagh** [comment]
Further improvements were included in v3.0.1
