### ISSUE TITLE
Error in diet average daily cost and requirements met

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#52]
Hi - I'm still getting doubled average daily diet costs and requirements are all showing as not met, despite using the same data from the old version of the software (see both examples attached). Also, the number of foods selected is slightly different for a couple of the diets.

Is it working for you? Are you using a more updated db3? I noticed the DB I replaced mine with a larger file size.

<img width="892" alt="Costs_new version" src="https://user-images.githubusercontent.com/89542648/176656665-40e55464-5550-465d-bac7-b1dd6df496dc.PNG">
<img width="845" alt="Costs_old version" src="https://user-images.githubusercontent.com/89542648/176656682-0836cae5-00d4-45c4-bb0c-86e8019fbf54.PNG">

**Comment by DavidKavanagh** [comment]
Could you please test this again in release 2.3.10. Somehow the earlier fix for this issue became partially reverted but it seems to be fine again now. The team will investigate how that happened.

**Comment by DavidKavanagh** [comment]
This appears to be working fine in v3.0.0
