### ISSUE TITLE
Not able to add more markets and villages to test 'last updated'

### ISSUE THREAD

**Issue by jlhems** [SaveTheChildrenUK/CostOfTheDiet#53]
I've tried to add more markets and villages to test the 'last updated' field updates. When I click on Save nothing happens and the new markets and villages are not showing.

**Comment by DavidKavanagh** [comment]
Could you please try this in release 2.3.10 as it seems to be working for me now. There was a database issue in the previous release which may have caused this problem.

**Comment by DavidKavanagh** [comment]
Fixed in v3.0.3
